GET http://localhost:5000/api/corsoPadel

###
POST http://localhost:5000/api/corsoPadel
Content-Type: application/json

{
      "avatar":"https://tse4.mm.bing.net/th?id=OIP.kQORLV18xa1HKuZOQOuiSwHaIb&pid=Api&P=0&h=180",
      "price":20,
      "descrizioneCorso": "Corso Base"
}