### get all products
GET http://localhost:5000/api/prodottiVenduti

###
POST http://localhost:5000/api/prodottiVenduti
Content-Type: application/json

{
     "avatar": "",
      "price":"120",
      "brand": "babolat",
}