@baseUrl=http://localhost:5000/api/profiles

POST {{baseUrl}}
Content-Type: application/json

{
     "name": "samuele",
      "surname":"calabrese",
      "email": "samuelecala@samueccccclecala.it",
      "password":"123456"
}

###

GET {{baseUrl}}

###

GET {{baseUrl}}/66ec603503202d65c39518e5


###

PUT {{baseUrl}}/66ec603503202d65c39518e5
Content-Type: application/json

{
      "name": "samuele",
      "username":"calabrese",
      "email": "samu.samu@samu.it",
      "password":"12345"
} 

###

DELETE {{baseUrl}}/66ec68b910de1eb5af9137f5